#!/usr/bin/env bash
set -euo pipefail

BASE="/Users/xixi/auto-sas-analytics/apps/web"

mkdir -p \
  "$BASE/app/tasks/new" \
  "$BASE/app/tasks/[taskId]" \
  "$BASE/app/system" \
  "$BASE/lib"

cat <<'EOF2' > "$BASE/package.json"
{
  "name": "auto-sas-analytics-web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 3000",
    "build": "next build",
    "start": "next start -p 3000"
  },
  "dependencies": {
    "next": "14.2.15",
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
  "devDependencies": {
    "@types/node": "22.10.2",
    "@types/react": "18.3.12",
    "@types/react-dom": "18.3.1",
    "typescript": "5.6.3"
  }
}
EOF2

cat <<'EOF2' > "$BASE/tsconfig.json"
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF2

cat <<'EOF2' > "$BASE/next.config.js"
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true
};

module.exports = nextConfig;
EOF2

cat <<'EOF2' > "$BASE/next-env.d.ts"
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is auto-generated by Next.js
EOF2

cat <<'EOF2' > "$BASE/.env.example"
NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:8000
EOF2

cat <<'EOF2' > "$BASE/app/layout.tsx"
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Auto SAS Analytics",
  description: "Automated SAS Analytics Platform MVP"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          fontFamily: "Arial, sans-serif",
          background: "#f7f7fb",
          color: "#111"
        }}
      >
        <div
          style={{
            maxWidth: 1000,
            margin: "0 auto",
            padding: "24px"
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
EOF2

cat <<'EOF2' > "$BASE/lib/api.ts"
const API_BASE =
  process.env.NEXT_PUBLIC_API_BASE_URL || "http://127.0.0.1:8000";

export type Template = {
  id: string;
  slug: string;
  name: string;
  description: string;
};

export type TaskListItem = {
  id: string;
  status: string;
  created_at: string;
};

export type TaskDetail = {
  id: string;
  status: string;
  uploaded_file_id: string;
  template_id: string;
  delimiter: string;
  has_header: boolean;
  params_json: Record<string, unknown>;
  artifacts: Record<string, string>;
  error_message?: string | null;
  created_at: string;
  updated_at: string;
};

export type UploadResponse = {
  id: string;
  filename: string;
  file_type: string;
  storage_path: string;
};

export type RunTaskResponse = {
  id: string;
  status: string;
  artifacts: Record<string, string>;
  error_message?: string | null;
};

export async function getTemplates(): Promise<Template[]> {
  const res = await fetch(`${API_BASE}/api/templates`, { cache: "no-store" });
  if (!res.ok) throw new Error("Failed to load templates");
  return res.json();
}

export async function getTasks(): Promise<TaskListItem[]> {
  const res = await fetch(`${API_BASE}/api/tasks`, { cache: "no-store" });
  if (!res.ok) throw new Error("Failed to load tasks");
  return res.json();
}

export async function getTask(taskId: string): Promise<TaskDetail> {
  const res = await fetch(`${API_BASE}/api/tasks/${taskId}`, {
    cache: "no-store"
  });
  if (!res.ok) throw new Error("Failed to load task");
  return res.json();
}

export async function uploadFile(file: File): Promise<UploadResponse> {
  const formData = new FormData();
  formData.append("file", file);

  const res = await fetch(`${API_BASE}/api/uploads`, {
    method: "POST",
    body: formData
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(text || "Upload failed");
  }

  return res.json();
}

export async function createTask(payload: {
  uploaded_file_id: string;
  template_slug: string;
  delimiter: "comma" | "tab" | "space";
  has_header: boolean;
  params_json: Record<string, unknown>;
}): Promise<TaskDetail> {
  const res = await fetch(`${API_BASE}/api/tasks`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(payload)
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(text || "Create task failed");
  }

  return res.json();
}

export async function runTask(taskId: string): Promise<RunTaskResponse> {
  const res = await fetch(`${API_BASE}/api/tasks/${taskId}/run`, {
    method: "POST"
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(text || "Run task failed");
  }

  return res.json();
}

export async function getSystemCheck(): Promise<Record<string, unknown>> {
  const res = await fetch(`${API_BASE}/api/system/check`, { cache: "no-store" });
  if (!res.ok) throw new Error("Failed to load system check");
  return res.json();
}
EOF2

cat <<'EOF2' > "$BASE/app/page.tsx"
import Link from "next/link";

const cardStyle: React.CSSProperties = {
  background: "#fff",
  padding: 20,
  borderRadius: 12,
  boxShadow: "0 1px 4px rgba(0,0,0,0.08)"
};

const linkStyle: React.CSSProperties = {
  display: "inline-block",
  padding: "10px 14px",
  background: "#111827",
  color: "#fff",
  borderRadius: 8,
  textDecoration: "none",
  marginRight: 12,
  marginBottom: 12
};

export default function HomePage() {
  return (
    <main>
      <h1 style={{ fontSize: 32, marginBottom: 8 }}>Auto SAS Analytics</h1>
      <p style={{ color: "#444", marginBottom: 24 }}>
        Automated SAS Analytics Platform MVP for upload, task creation, task run,
        and report inspection.
      </p>

      <div style={cardStyle}>
        <h2>Quick Actions</h2>
        <div style={{ marginTop: 16 }}>
          <Link href="/tasks/new" style={linkStyle}>
            Go to New Task
          </Link>
          <Link href="/tasks" style={linkStyle}>
            Go to Task List
          </Link>
          <Link href="/system" style={linkStyle}>
            Go to System Check
          </Link>
        </div>
      </div>
    </main>
  );
}
EOF2

cat <<'EOF2' > "$BASE/app/tasks/page.tsx"
"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getTasks, TaskListItem } from "@/lib/api";

export default function TasksPage() {
  const [tasks, setTasks] = useState<TaskListItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    getTasks()
      .then(setTasks)
      .catch((err) => setError(err.message || "Failed to load tasks"))
      .finally(() => setLoading(false));
  }, []);

  return (
    <main>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <h1>Tasks</h1>
        <Link href="/tasks/new">New Task</Link>
      </div>

      {loading && <p>Loading tasks...</p>}
      {error && <p style={{ color: "crimson" }}>{error}</p>}

      {!loading && !error && tasks.length === 0 && (
        <div
          style={{
            background: "#fff",
            padding: 16,
            borderRadius: 12,
            marginTop: 12
          }}
        >
          No tasks yet.
        </div>
      )}

      {!loading && !error && tasks.length > 0 && (
        <div style={{ display: "grid", gap: 12, marginTop: 16 }}>
          {tasks.map((task) => (
            <Link
              key={task.id}
              href={`/tasks/${task.id}`}
              style={{
                textDecoration: "none",
                color: "inherit",
                background: "#fff",
                padding: 16,
                borderRadius: 12,
                boxShadow: "0 1px 4px rgba(0,0,0,0.08)"
              }}
            >
              <div><strong>ID:</strong> {task.id}</div>
              <div><strong>Status:</strong> {task.status}</div>
              <div><strong>Created:</strong> {task.created_at}</div>
            </Link>
          ))}
        </div>
      )}
    </main>
  );
}
EOF2

cat <<'EOF2' > "$BASE/app/tasks/new/page.tsx"
"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createTask, getTemplates, Template, uploadFile } from "@/lib/api";

export default function NewTaskPage() {
  const router = useRouter();

  const [templates, setTemplates] = useState<Template[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState("");
  const [delimiter, setDelimiter] = useState<"comma" | "tab" | "space">("comma");
  const [hasHeader, setHasHeader] = useState(true);
  const [file, setFile] = useState<File | null>(null);

  const [loadingTemplates, setLoadingTemplates] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    getTemplates()
      .then((data) => {
        setTemplates(data);
        if (data.length > 0) setSelectedTemplate(data[0].slug);
      })
      .catch((err) => setError(err.message || "Failed to load templates"))
      .finally(() => setLoadingTemplates(false));
  }, []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    if (!file) {
      setError("Please choose a CSV or TXT file.");
      return;
    }

    if (!selectedTemplate) {
      setError("Please choose a template.");
      return;
    }

    try {
      setSubmitting(true);
      const uploaded = await uploadFile(file);
      const task = await createTask({
        uploaded_file_id: uploaded.id,
        template_slug: selectedTemplate,
        delimiter,
        has_header: hasHeader,
        params_json: {}
      });
      router.push(`/tasks/${task.id}`);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create task");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <main>
      <h1>New Task</h1>

      {loadingTemplates && <p>Loading templates...</p>}
      {error && (
        <div
          style={{
            background: "#ffe5e5",
            color: "#8b0000",
            padding: 12,
            borderRadius: 10,
            marginBottom: 16
          }}
        >
          {error}
        </div>
      )}

      <form
        onSubmit={handleSubmit}
        style={{
          display: "grid",
          gap: 16,
          background: "#fff",
          padding: 20,
          borderRadius: 12,
          boxShadow: "0 1px 4px rgba(0,0,0,0.08)"
        }}
      >
        <div>
          <label>File</label>
          <br />
          <input
            type="file"
            accept=".csv,.txt"
            onChange={(e) => setFile(e.target.files?.[0] || null)}
          />
        </div>

        <div>
          <label>Template</label>
          <br />
          <select
            value={selectedTemplate}
            onChange={(e) => setSelectedTemplate(e.target.value)}
          >
            {templates.map((tpl) => (
              <option key={tpl.id} value={tpl.slug}>
                {tpl.name} ({tpl.slug})
              </option>
            ))}
          </select>
        </div>

        <div>
          <label>Delimiter</label>
          <br />
          <select
            value={delimiter}
            onChange={(e) => setDelimiter(e.target.value as "comma" | "tab" | "space")}
          >
            <option value="comma">comma</option>
            <option value="tab">tab</option>
            <option value="space">space</option>
          </select>
        </div>

        <div>
          <label>
            <input
              type="checkbox"
              checked={hasHeader}
              onChange={(e) => setHasHeader(e.target.checked)}
            />{" "}
            Has Header
          </label>
        </div>

        <button
          type="submit"
          disabled={submitting}
          style={{
            padding: "10px 14px",
            borderRadius: 8,
            border: "none",
            background: "#111827",
            color: "#fff",
            cursor: "pointer"
          }}
        >
          {submitting ? "Creating..." : "Create Task"}
        </button>
      </form>
    </main>
  );
}
EOF2

cat <<'EOF2' > "$BASE/app/tasks/[taskId]/page.tsx"
"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { getTask, runTask, TaskDetail } from "@/lib/api";

export default function TaskDetailPage() {
  const params = useParams<{ taskId: string }>();
  const taskId = useMemo(() => {
    const raw = params?.taskId;
    return Array.isArray(raw) ? raw[0] : raw;
  }, [params]);

  const [task, setTask] = useState<TaskDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState("");

  async function refresh() {
    if (!taskId) return;
    const data = await getTask(taskId);
    setTask(data);
  }

  useEffect(() => {
    if (!taskId) return;

    setLoading(true);
    getTask(taskId)
      .then(setTask)
      .catch((err) => setError(err.message || "Failed to load task"))
      .finally(() => setLoading(false));
  }, [taskId]);

  useEffect(() => {
    if (!task) return;
    if (task.status !== "pending" && task.status !== "running") return;

    const timer = setInterval(() => {
      refresh().catch(() => {});
    }, 2000);

    return () => clearInterval(timer);
  }, [task]);

  async function handleRun() {
    if (!taskId) return;
    setError("");
    try {
      setRunning(true);
      await runTask(taskId);
      await refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to run task");
    } finally {
      setRunning(false);
    }
  }

  return (
    <main>
      <h1>Task Detail</h1>

      {loading && <p>Loading task...</p>}
      {error && (
        <div
          style={{
            background: "#ffe5e5",
            color: "#8b0000",
            padding: 12,
            borderRadius: 10,
            marginBottom: 16
          }}
        >
          {error}
        </div>
      )}

      {task && (
        <div
          style={{
            display: "grid",
            gap: 16
          }}
        >
          <div
            style={{
              background: "#fff",
              padding: 20,
              borderRadius: 12,
              boxShadow: "0 1px 4px rgba(0,0,0,0.08)"
            }}
          >
            <div><strong>ID:</strong> {task.id}</div>
            <div><strong>Status:</strong> {task.status}</div>
            <div><strong>Uploaded File ID:</strong> {task.uploaded_file_id}</div>
            <div><strong>Template ID:</strong> {task.template_id}</div>
            <div><strong>Delimiter:</strong> {task.delimiter}</div>
            <div><strong>Has Header:</strong> {String(task.has_header)}</div>
            {task.error_message && (
              <div style={{ marginTop: 12, color: "crimson" }}>
                <strong>Error:</strong> {task.error_message}
              </div>
            )}

            {(task.status === "pending" || task.status === "running") && (
              <button
                onClick={handleRun}
                disabled={running || task.status === "running"}
                style={{
                  marginTop: 16,
                  padding: "10px 14px",
                  borderRadius: 8,
                  border: "none",
                  background: "#111827",
                  color: "#fff",
                  cursor: "pointer"
                }}
              >
                {task.status === "running" ? "Running..." : running ? "Running..." : "Run Task"}
              </button>
            )}
          </div>

          {task.artifacts && Object.keys(task.artifacts).length > 0 && (
            <div
              style={{
                background: "#fff",
                padding: 20,
                borderRadius: 12,
                boxShadow: "0 1px 4px rgba(0,0,0,0.08)"
              }}
            >
              <h2>Artifacts</h2>
              <ul>
                {Object.entries(task.artifacts).map(([key, value]) => (
                  <li key={key}>
                    <strong>{key}:</strong>{" "}
                    <a href={value} target="_blank" rel="noreferrer">
                      Open
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {task.artifacts?.report && (
            <div
              style={{
                background: "#fff",
                padding: 20,
                borderRadius: 12,
                boxShadow: "0 1px 4px rgba(0,0,0,0.08)"
              }}
            >
              <h2>Report Preview</h2>
              <iframe
                src={task.artifacts.report}
                style={{
                  width: "100%",
                  height: 500,
                  border: "1px solid #ddd",
                  borderRadius: 8
                }}
              />
            </div>
          )}
        </div>
      )}
    </main>
  );
}
EOF2

cat <<'EOF2' > "$BASE/app/system/page.tsx"
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { getSystemCheck } from "@/lib/api";

export default function SystemPage() {
  const [data, setData] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    getSystemCheck()
      .then(setData)
      .catch((err) => setError(err.message || "Failed to load system check"))
      .finally(() => setLoading(false));
  }, []);

  return (
    <main>
      <h1>System Check</h1>
      <p>
        <Link href="/">Back Home</Link>
      </p>

      {loading && <p>Loading system check...</p>}
      {error && <p style={{ color: "crimson" }}>{error}</p>}

      {data && (
        <pre
          style={{
            background: "#fff",
            padding: 20,
            borderRadius: 12,
            boxShadow: "0 1px 4px rgba(0,0,0,0.08)",
            overflow: "auto"
          }}
        >
          {JSON.stringify(data, null, 2)}
        </pre>
      )}
    </main>
  );
}
EOF2

echo "Frontend files created under: $BASE"
echo "Next steps:"
echo "  cd $BASE"
echo "  cp .env.example .env.local"
echo "  npm install"
echo "  npm run dev"
