from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.analysis_template import AnalysisTemplate


DEFAULT_TEMPLATES = [
    {
        "name": "Descriptive Report (Python)",
        "slug": "descriptive-report-python",
        "description": "Descriptive statistics report generated by the Python engine.",
        "runner_type": "python",
        "engine": "python",
        "is_active": True,
        "sas_script_path": "app/templates/descriptive_report.sas",
    },
    {
        "name": "Descriptive Report (SAS)",
        "slug": "descriptive-report-sas",
        "description": "Descriptive statistics report template for SAS engine.",
        "runner_type": "sas",
        "engine": "sas",
        "is_active": True,
        "sas_script_path": "app/templates/descriptive_report.sas",
    },
]


def seed_data(db: Session) -> None:
    for template_data in DEFAULT_TEMPLATES:
        existing = db.scalar(
            select(AnalysisTemplate).where(AnalysisTemplate.slug == template_data["slug"])
        )
        if existing:
            existing.name = template_data["name"]
            existing.description = template_data["description"]
            existing.runner_type = template_data["runner_type"]
            existing.engine = template_data["engine"]
            existing.is_active = template_data["is_active"]
            if getattr(existing, "sas_script_path", None) in (None, ""):
                existing.sas_script_path = template_data["sas_script_path"]
            db.add(existing)
            continue

        db.add(AnalysisTemplate(**template_data))

    db.commit()
